export { default as Productss} from '../../assets/img/product/product.jpg';
export { default as Product1} from '../../assets/img/product/product1.jpg';
export { default as Product2} from '../../assets/img/product/product2.jpg';
export { default as Product10} from '../../assets/img/product/product10.jpg';
export { default as Product11} from '../../assets/img/product/product11.jpg';
export { default as Product12} from '../../assets/img/product/product12.jpg';
export { default as Product13} from '../../assets/img/product/product13.jpg';
export { default as Product14} from '../../assets/img/product/product14.jpg';
export { default as Product3} from '../../assets/img/product/product3.jpg';